#!/bin/bash


# Define a few commands.
ECHO=/usr/bin/echo
CAT=/usr/bin/cat
LOFIADM=/usr/sbin/lofiadm
MKISOFS=/usr/bin/mkisofs
TIME=/usr/bin/time

PKG_IMG_PATH=$2
if [ ! -d $PKG_IMG_PATH ] ; then
	print -u2 -f "%s: Image package area %s is not valid\n" \
	    "$0" "$PKG_IMG_PATH"
	exit 1
fi

/usr/gnu/bin/cp help/C/* $PKG_IMG_PATH/usr/share/text-install/help/C/
/usr/gnu/bin/cp text-mode-menu $PKG_IMG_PATH/usr/sbin/
/usr/gnu/bin/cp osol_install/ict.py $PKG_IMG_PATH/usr/lib/python2.6/vendor-packages/osol_install/
/usr/gnu/bin/cp osol_install/text_install/*.py $PKG_IMG_PATH/usr/lib/python2.6/vendor-packages/osol_install/text_install/
